CREATE TABLE thiagocosta_65573.users (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	hash VARCHAR(33) NOT NULL
);

CREATE TABLE thiagocosta_65573.control (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	message VARCHAR(100) NOT NULL,
	date DATETIME default NOW()
);